<a href="https://colab.research.google.com/github/GyaaniJ/pytorch-deep-learning/blob/Learning/PyTorch_Workflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


In [ ]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([[7,7]])
vector

tensor([[7, 7]])

In [ ]:
vector.ndim

2

In [ ]:
matrix = torch.tensor([[[3,3]]])
matrix.ndim
matrix.shape

torch.Size([1, 1, 2])

In [ ]:
matrix.ndim

3

In [ ]:
print(torch.tensor)

<built-in method tensor of type object at 0x7cb8fb081760>


## random tensors


In [ ]:
random_tensor = torch.rand(3,4,4)

In [ ]:
print(random_tensor)

tensor([[[0.0443, 0.2355, 0.8918, 0.6370],
         [0.2828, 0.0758, 0.9330, 0.2932],
         [0.8911, 0.0571, 0.8859, 0.2680],
         [0.0267, 0.0864, 0.5586, 0.2052]],

        [[0.9772, 0.2367, 0.2433, 0.9581],
         [0.0123, 0.0169, 0.8054, 0.1302],
         [0.8308, 0.7477, 0.5808, 0.5686],
         [0.7518, 0.5181, 0.9131, 0.6576]],

        [[0.5318, 0.4184, 0.1653, 0.8230],
         [0.9276, 0.9409, 0.6686, 0.1682],
         [0.9298, 0.5291, 0.8807, 0.7504],
         [0.3706, 0.9467, 0.8501, 0.2355]]])


In [ ]:
random_tensor

tensor([[[0.0443, 0.2355, 0.8918, 0.6370],
         [0.2828, 0.0758, 0.9330, 0.2932],
         [0.8911, 0.0571, 0.8859, 0.2680],
         [0.0267, 0.0864, 0.5586, 0.2052]],

        [[0.9772, 0.2367, 0.2433, 0.9581],
         [0.0123, 0.0169, 0.8054, 0.1302],
         [0.8308, 0.7477, 0.5808, 0.5686],
         [0.7518, 0.5181, 0.9131, 0.6576]],

        [[0.5318, 0.4184, 0.1653, 0.8230],
         [0.9276, 0.9409, 0.6686, 0.1682],
         [0.9298, 0.5291, 0.8807, 0.7504],
         [0.3706, 0.9467, 0.8501, 0.2355]]])

In [ ]:
random_image_size = torch.rand(size=(224,224,3))
random_image_size.shape

torch.Size([224, 224, 3])

In [ ]:
# randomtensor1 = torch.rand(224,224,3,4)
# print(randomtensor1)

#create a tensor of all zeros

In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
y = torch.ones(3,4)
y

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
y.dtype

torch.float32

# the default type is float32

### Creating a range of tensors and tensors like object

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y1 = torch.arange(start = 3, end = 30, step = 2)

In [ ]:
y1

tensor([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [ ]:
ten_zeros = torch.zeros_like(y1)
ten_zeros
ten_ones = torch.ones_like(y1)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## torch datatypes

In [ ]:
data1 = torch.rand(size=(5,4,5))
data2 = [3,4,5]

In [ ]:
float_32_tensor1 = torch.tensor(data= data2, dtype = None)
float_32_tensor1

tensor([3, 4, 5])

In [ ]:
float_tensor1 = torch.tensor([3,5,6,7], dtype = torch.float32, requires_grad = True)
float_tensor1.dtype

torch.float32

In [ ]:
y3 = torch.tensor([4,88,9], dtype = torch.float32)
y3

tensor([ 4., 88.,  9.])

# Getting information

In [ ]:
y3.dtype

torch.float32

In [ ]:
y3.shape

torch.Size([3])

In [ ]:
y3.device

device(type='cpu')

In [ ]:
print(f"Datatype of y3 is {y3.dtype}")

Datatype of y3 is torch.float32


In [ ]:
tensor1 = torch.tensor([1,2,3,4])
tensor1 + 10

tensor([11, 12, 13, 14])

In [ ]:
torch.add(tensor1,20)

tensor([21, 22, 23, 24])

In [ ]:
torch.mul(tensor1,10)

tensor([10, 20, 30, 40])

# element wise multipation

In [ ]:
print(tensor1 * tensor1)

tensor([ 1,  4,  9, 16])


In [ ]:
print(tensor1.T)

tensor([1, 2, 3, 4])


In [ ]:
torch.matmul(tensor1.T, tensor1.T)


tensor(30)

In [ ]:
x1 = torch.tensor([[1,2,3],[1,2,3]])
x1.shape

torch.Size([2, 3])

In [ ]:
x2 = torch.tensor([[1,2],[1,2],[1,2]])
x2.shape

torch.Size([3, 2])

In [ ]:
x1* x2.T

tensor([[1, 2, 3],
        [2, 4, 6]])

In [ ]:
torch.matmul(x1,x2)

tensor([[ 6, 12],
        [ 6, 12]])

In [ ]:
y = torch.arange(11)
y

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.mean(y.type(torch.float32))

tensor(5.)

In [ ]:
y

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
y.argmax()

tensor(10)

In [ ]:
z = y.reshape(11,1)

In [ ]:
z[1]=2
z


tensor([[ 0],
        [ 2],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])

In [ ]:
y

tensor([ 0,  2,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Original tensor:")
print(tensor)
print("Shape:", tensor.shape)


Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])


In [ ]:
# Using view to reshape the tensor (shares memory)
tensor_view = tensor.view(3, 2)
print("\nTensor after view (shares memory):")
print(tensor_view)
print("Shape:", tensor_view.shape)



Tensor after view (shares memory):
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Shape: torch.Size([3, 2])


In [ ]:
# Modify the view and check the original tensor
tensor_view[0, 0] = 99
print("\nModified tensor view:")
print(tensor_view)
print("Original tensor after modifying view:")
print(tensor)


Modified tensor view:
tensor([[99,  2],
        [ 3,  4],
        [ 5,  6]])
Original tensor after modifying view:
tensor([[99,  2,  3],
        [ 4,  5,  6]])


In [ ]:
# Using reshape to reshape the tensor (shares memory if contiguous)
tensor_reshape = tensor.reshape(3, 2)
print("\nTensor after reshape (shares memory if contiguous):")
print(tensor_reshape)
print("Shape:", tensor_reshape.shape)


Tensor after reshape (shares memory if contiguous):
tensor([[99,  2],
        [ 3,  4],
        [ 5,  6]])
Shape: torch.Size([3, 2])


In [ ]:
# Modify the reshape and check the original tensor
tensor_reshape[1, 0] = 88
print("\nModified tensor reshape:")
print(tensor_reshape)
print("Original tensor after modifying reshape:")
print(tensor)


Modified tensor reshape:
tensor([[99,  2],
        [88,  4],
        [ 5,  6]])
Original tensor after modifying reshape:
tensor([[99,  2, 88],
        [ 4,  5,  6]])


In [ ]:
# Create a non-contiguous tensor by transposing
tensor_t = tensor.t()
print("\nTransposed tensor (non-contiguous):")
print(tensor_t)
print("Shape:", tensor_t.shape)
print("Is contiguous:", tensor_t.is_contiguous())


Transposed tensor (non-contiguous):
tensor([[99,  4],
        [ 2,  5],
        [88,  6]])
Shape: torch.Size([3, 2])
Is contiguous: False


In [ ]:
# Using reshape on a non-contiguous tensor (does not share memory)
tensor_t_reshape = tensor_t.reshape(3, 2)
print("\nTensor after reshape on non-contiguous tensor (does not share memory):")
print(tensor_t_reshape)
print("Shape:", tensor_t_reshape.shape)


Tensor after reshape on non-contiguous tensor (does not share memory):
tensor([[99,  4],
        [ 2,  5],
        [88,  6]])
Shape: torch.Size([3, 2])


In [ ]:
# Modify the reshape and check the original tensor
tensor_t_reshape[2, 0] = 77
print("\nModified tensor reshape on non-contiguous tensor:")
print(tensor_t_reshape)
print("Original transposed tensor after modifying reshape:")
print(tensor_t)
print("Original tensor after modifying reshape:")
print(tensor)


Modified tensor reshape on non-contiguous tensor:
tensor([[99,  4],
        [ 2,  5],
        [77,  6]])
Original transposed tensor after modifying reshape:
tensor([[99,  4],
        [ 2,  5],
        [77,  6]])
Original tensor after modifying reshape:
tensor([[99,  2, 77],
        [ 4,  5,  6]])


In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Original tensor:")
print(tensor)
print("Shape:", tensor.shape)
print("Is contiguous:", tensor.is_contiguous())

Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
Is contiguous: True


In [ ]:
reshaped_tensor = tensor.reshape(3, 2)
print("\nReshaped tensor (shares memory if contiguous):")
print(reshaped_tensor)
print("Shape:", reshaped_tensor.shape)
print("Is contiguous:", reshaped_tensor.is_contiguous())


Reshaped tensor (shares memory if contiguous):
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Shape: torch.Size([3, 2])
Is contiguous: True


In [ ]:
# Modify the reshaped tensor and check the original tensor
reshaped_tensor[0, 0] = 99
print("\nModified reshaped tensor:")
print(reshaped_tensor)
print("Original tensor after modifying reshaped tensor:")
print(tensor)


Modified reshaped tensor:
tensor([[99,  2],
        [ 3,  4],
        [ 5,  6]])
Original tensor after modifying reshaped tensor:
tensor([[99,  2,  3],
        [ 4,  5,  6]])


In [ ]:
# Create a non-contiguous tensor by transposing the original tensor
non_contiguous_tensor = tensor.t()
print("\nTransposed tensor (non-contiguous):")
print(non_contiguous_tensor)
print("Shape:", non_contiguous_tensor.shape)
print("Is contiguous:", non_contiguous_tensor.is_contiguous())

# Using reshape on a non-contiguous tensor (does not share memory)
reshaped_non_contiguous_tensor = non_contiguous_tensor.reshape(3, 2)
print("\nReshaped non-contiguous tensor (does not share memory):")
print(reshaped_non_contiguous_tensor)
print("Shape:", reshaped_non_contiguous_tensor.shape)
print("Is contiguous:", reshaped_non_contiguous_tensor.is_contiguous())

# Modify the reshaped non-contiguous tensor and check the original tensor
reshaped_non_contiguous_tensor[0, 0] = 88
print("\nModified reshaped non-contiguous tensor:")
print(reshaped_non_contiguous_tensor)
print("Transposed tensor after modifying reshaped tensor:")
print(non_contiguous_tensor)
print("Original tensor after modifying reshaped tensor:")
print(tensor)



Transposed tensor (non-contiguous):
tensor([[99,  4],
        [ 2,  5],
        [ 3,  6]])
Shape: torch.Size([3, 2])
Is contiguous: False

Reshaped non-contiguous tensor (does not share memory):
tensor([[99,  4],
        [ 2,  5],
        [ 3,  6]])
Shape: torch.Size([3, 2])
Is contiguous: False

Modified reshaped non-contiguous tensor:
tensor([[88,  4],
        [ 2,  5],
        [ 3,  6]])
Transposed tensor after modifying reshaped tensor:
tensor([[88,  4],
        [ 2,  5],
        [ 3,  6]])
Original tensor after modifying reshaped tensor:
tensor([[88,  2,  3],
        [ 4,  5,  6]])


In [ ]:
x_reshaped = torch.tensor([[5,2,3,4,5,6,7,8,9]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
y=x_reshaped.squeeze()

In [ ]:
y.shape

torch.Size([9])

In [ ]:
x =torch.randn (2,3,5)
x.size()
torch.permute(x,(2,0,1)).size()

torch.Size([5, 2, 3])

In [ ]:
uniform_tensor = torch.rand(2,3)
print(f'uniform_tensor: {uniform_tensor}')

uniform_tensor: tensor([[0.9641, 0.2673, 0.7357],
        [0.6767, 0.4770, 0.1761]])


In [ ]:
normal_tensor = torch.randn(2,3)
print(f'normal tensor: {normal_tensor}')

normal tensor: tensor([[ 0.5468,  1.3237,  0.9811],
        [ 1.0580,  0.0272, -0.7472]])


In [ ]:
normal_tensor.mean(dim= 1)

tensor([0.9505, 0.1126])

In [ ]:
uniform_tensor.mean(dim = 1)

tensor([0.6557, 0.4433])

In [ ]:
import torch

# Generate a large tensor with random values from a normal distribution
large_tensor = torch.randn(2,3)

# Calculate the mean
mean = large_tensor.mean()
print(f"Mean: {mean}")

# Calculate the standard deviation
std_dev = large_tensor.std()
print(f"Standard Deviation: {std_dev}")


Mean: -0.23620356619358063
Standard Deviation: 1.2462807893753052


In [ ]:
# Generate a tensor with shape (3, 4) using torch.randn
random_tensor = torch.randn(3, 4)

# Calculate the mean
mean_value = random_tensor.mean()

# Calculate the standard deviation
std_value = random_tensor.std()

# Print the tensor, mean, and standard deviation
print("Generated Tensor:")
print(random_tensor)
print(f"\nMean: {mean_value}")
print(f"Standard Deviation: {std_value}")


Generated Tensor:
tensor([[-0.3555, -0.1622,  0.4854, -0.4713],
        [ 0.8638,  2.0376,  0.1966, -1.5566],
        [ 0.5034,  0.0148, -1.3377,  1.4496]])

Mean: 0.13898909091949463
Standard Deviation: 1.039345383644104


In [ ]:
random_permute = print(random_tensor.permute(1,0).shape)

torch.Size([4, 3])


In [ ]:
random_tensor[0,:]

tensor([-0.3555, -0.1622,  0.4854, -0.4713])

In [ ]:
import numpy as np

In [ ]:
array = np.arange(1,8)
tensor = torch.from_numpy(array)
tensor.dtype

torch.int64

In [ ]:
numpy_array = tensor.numpy()

In [ ]:
import torch
torch.cuda.is_available()

False